version: "3"

services:
  app:
    build:
      context: ./app
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    volumes:
      - ./app:/usr/src/app/
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - node-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  server:
    restart: always
    container_name: server
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
