version: "3"
services:
  nodeserver:
    build:
      context: ./app
    container_name: app
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "8080:80"
